#ifndef CLIENT_HARD_CODE_H
#define CLIENT_HARD_CODE_H
#define NUM_OF_INPUTS 3
#define SERVER_IP_IND 1
#define SERVER_PORT_IND 2
#define USERNAME_IND 2
#define ERROR_CODE 1
#define SUCCESS_CODE 0
#define USER_INPUT_BASE_SIZE 10
#endif // !CLIENT_HARD_CODE_H

