#ifndef SERVER_HARD_CODED_H
#define SERVER_HARD_CODED_H
#define NUM_OF_INPUTS 1
#define PORT_NUM_IND 1
#define ERROR_CODE 1
#define SUCCESS_CODE 0
#define MAX_NUM_CLIENTS 3
#define MAX_NUM_PLAYERS 2
#define EVENT_NAME_LEN 30

#endif // !SERVER_HARD_CODED_H

